### ISSUE TITLE
changHeader.c? Why not just mkfs.c?

### ISSUE THREAD

**Issue by JianxinMa** [leopard1/v9-ucore#1]
我看了下你们的东西，你们好象是用changeHeader（这什么鬼）来载入程序的。但是正常情况下，应该是：用mkfs.c这个工具生成磁盘镜像（内容是启动模拟器时会被载入内存的文件系统），磁盘镜像包含用户程序，操作系统去磁盘找这个程序。

changeHeader是你们自己写的简化版mkfs？为什么要干这件事....

我这边前端的预处理器、编译器、mkfs都准备好了，就等你们的内容了。

**Comment by leix28** [comment]
我们暂时还没有启动文件系统，然后程序头里面不知道文件有多长，所以用changeHeader临时解决了一下。稍后加上文件系统就不用这个了。

**Comment by JianxinMa** [comment]
希望能去掉changeHeader，直接用mkfs.c。因为我提供的是mkfs.c，并不想再加个changeHeader。

**Comment by JianxinMa** [comment]
好的。
